homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret default_lat
  longitude: !secret default_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 364
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include includes/customize.yaml


# Owntracks
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 100

# Zones Below
zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 300
  icon: mdi:home

zone 1:
  name: School
  latitude: !secret school_lat
  longitude: !secret school_long
  radius: 300
  icon: mdi:school

# Wink 2 Hub
wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

#For ffmpeg cameras
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  

switch:
  - platform: edimax
    host: 192.168.0.199
    username: !secret edimax_username
    password: !secret edimax_password



media_player 1:
  - platform: directv
    host: 192.168.0.145

media_player 2:
  - platform: webostv
    host: 192.168.0.102
    name: LG WebosTV

media_player 3:
  - platform: directv
    host: 192.168.0.209

media_player 4:
   - platform: cast
     host: 192.168.0.146

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

# Amcrest Camera 1 - Living Room
camera:
  - platform: amcrest
    host: 192.168.0.207
    username: !secret amcrest_user_name
    password: !secret amcrest_password

# Simple Home Camera 1 - Back Yard
camera 1:
  - platform: ffmpeg
    name: Outcam
    input: -rtsp_transport tcp -i rtsp://home:home@10.1.0.158:554/11
    extra_arguments: -q:v 2 

# Amcrest Camera 2 - Driveway
camera 2:
  - platform: amcrest
    host: 192.168.0.147
    username: !secret amcrest_user_name
    password: !secret amcrest_password



# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

sensor:
  - platform: wunderground
    api_key:  ee3582efd25d7641
    monitored_conditions:
      - alerts
      - dewpoint_c
      - dewpoint_f
      - dewpoint_string
      - feelslike_c
      - feelslike_f
      - feelslike_string
      - heat_index_c
      - heat_index_f
      - heat_index_string
      - elevation
      - location
      - observation_time
      - precip_1hr_in
      - precip_1hr_metric
      - precip_1hr_string
      - precip_today_in
      - precip_today_metric
      - precip_today_string
      - pressure_in
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - station_id
      - solarradiation
      - temperature_string
      - temp_f
      - UV
      - visibility_km
      - visibility_mi
      - weather
      - wind_degrees
      - wind_dir
      - wind_gust_kph
      - wind_gust_mph
      - wind_kph
      - wind_mph
      - wind_string
  - platform: template
    sensors:
       edimax_watts:
         value_template: '{{ states.switch.edimax_smart_plug.attributes["current_power_mwh"] | float * 1000000 | round(2) }}'
         unit_of_measurement: 'W'
       edimax_amps:
         value_template: '{{ states.switch.edimax_smart_plug.attributes["current_power_mwh"] | float * 1000000/110 | round(2) }}'
         unit_of_measurement: 'Amps'

# Text to speech
tts:
  platform: google

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

sensor 1:
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload

sensor 2:
  - platform: fastdotcom
    minute:
      - 0
      - 30

group: !include includes/groups.yaml
